version: "3"
services:
  ichgram:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ichgram
    ports:
      - "3000:3000" # Исправлен отступ
    depends_on:
      - mongodb
    volumes:
      - ./server/.env:/app/.env

  frontichgram:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontichgram
    depends_on:
      - ichgram
    ports:
      - "3001:3001"

  mongodb:
    ports:
      - 27017:27017
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=ichgramm
    command: --auth --bind_ip 0.0.0.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
